update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,19 +45,19 @@ jobs:
     - name: Enable necessary APIs
       run: |
         apis_to_enable=(
-           "compute.googleapis.com"
-           "container.googleapis.com"
-           "cloudresourcemanager.googleapis.com"
-           "artifactregistry.googleapis.com"
+          "compute.googleapis.com"
+          "container.googleapis.com"
+          "cloudresourcemanager.googleapis.com"
+          "artifactregistry.googleapis.com"
         )
         for api in "${apis_to_enable[@]}"; do
           if gcloud services list --enabled --filter="name:$api" --format="value(name)" | grep -q "$api"; then
-             echo "$api is already enabled"
-        else
-           echo "Enabling $api..."
-           gcloud services enable $api || echo "Failed to enable $api, it may require manual intervention"
-        fi
-     done
+            echo "$api is already enabled"
+          else
+            echo "Enabling $api..."
+            gcloud services enable $api || echo "Failed to enable $api, it may require manual intervention"
+          fi
+        done
 
     - name: Grant permissions to service account
       run: |
@@ -129,7 +129,7 @@ jobs:
     - name: Terraform Apply
       run: |
         for i in {1..3}; do
-          if terraform apply -auto-approve tfplan; then
+          if terraform apply -auto-approve; then
             echo "Terraform apply succeeded"
             break
           fi
@@ -167,7 +167,7 @@ jobs:
 
     - name: Verify API
       run: |
-        LOAD_BALANCER_IP=$(terraform output -raw load_balancer_ip)
+        LOAD_BALANCER_IP=$(kubectl get service assignment-service -n assignment -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
         for i in {1..30}; do
           response=$(curl -s -o /dev/null -w "%{http_code}" http://$LOAD_BALANCER_IP:3000)
           if [ $response -eq 200 ]; then
